version: 0.2

# AWS CodeBuild 빌드 스펙
# CodePipeline과 함께 사용하기 위한 설정

env:
  variables:
    NODE_ENV: production
    NODE_VERSION: "20"
  parameter-store:
    # AWS Systems Manager Parameter Store에 저장된 환경 변수
    # 예: DATABASE_URL: /wine-admin/prod/database-url
    # 예: FIREBASE_KEY: /wine-admin/prod/firebase-key
  secrets-manager:
    # AWS Secrets Manager에 저장된 비밀 정보
    # 예: DB_PASSWORD: wine-admin-prod:password

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies..."
      - node --version
      - npm --version
      - npm ci

  pre_build:
    commands:
      - echo "Running tests..."
      - npm run test --workspace=server || true
      - echo "Pre-build completed"

  build:
    commands:
      - echo "Building client application..."
      - npm run build:client
      - echo "Build completed"

  post_build:
    commands:
      - echo "Post-build phase"
      - |
        if [ $CODEBUILD_BUILD_SUCCEEDING -eq 1 ]; then
          echo "Build succeeded"
        else
          echo "Build failed"
          exit 1
        fi

artifacts:
  files:
    # 서버 파일
    - 'server/**/*'
    - 'shared/**/*'
    - 'package.json'
    - 'package-lock.json'
    # 빌드된 클라이언트 파일
    - 'client/build/**/*'
  name: wine-admin-$(date +%Y-%m-%d-%H-%M-%S)

cache:
  paths:
    - 'node_modules/**/*'
    - 'server/node_modules/**/*'
    - 'client/node_modules/**/*'
    - 'shared/node_modules/**/*'


